Repository akaihola/pgtricks, pull requests merged in 2024-04, with the labels that each got.

#22 Remove double quotes from filenames
  pgtricks/pg_split_schema_dump.py
  pgtricks/tests/test_pg_split_schema_dump.py
Labels: bugfix

#23 Enable development & releasing tools from darkgray-dev-tools
  CHANGES.rst
  CONTRIBUTORS.rst
  README.rst
  contributors.yaml
  pgtricks/version.py
  pyproject.toml
  release_tools/bump-version-patterns.yaml
  setup.cfg
Labels: documentation, CI

#25 README: Badges, call for help, stargazers
  README.rst
Labels: documentation

#16 Change to GitHub Actions build badge in README
  README.rst
Labels: documentation

#18 Try out Darker GitHub Action
  .github/workflows/python-package.yml
  pgtricks/pg_dump_splitsort.py
Labels: CI

#27 Add CI builds for Python 3.10, 3.11 and 3.12
  .github/workflows/python-package.yml
  CHANGES.rst
  setup.cfg
Labels: CI

#13 Support large tables which don't fit in RAM
  CHANGES.rst
  mypy.ini
  pgtricks/mergesort.py
  pgtricks/pg_dump_splitsort.py
  pgtricks/tests/test_mergesort.py
  pgtricks/tests/test_pg_dump_splitsort.py
  pyproject.toml
Labels: enhancement

#19 Treat empty tables the same as non-empty tables
  CHANGES.rst
  pgtricks/pg_dump_splitsort.py
  pgtricks/tests/test_pg_dump_splitsort.py
Labels: bugfix

#28 Release 1.1.0
  CHANGES.rst
  README.rst
  pgtricks/version.py
Labels: release
